### PR TITLE
Fix Make the generated test testable in container

### PR DESCRIPTION
**Pull request by danielsoro**

### CODE REVIEW

**Comment by aslakknutsen** [comment]
testable=false makes it not testable in container.. 

Tho we should/could attempt to infer the run mode based on the class under test.

.e.g. 
- a CDI / EJB = testable true
- REST Service = testable false

**Comment by danielsoro** [comment]
@aslakknutsen 
Maybe is better:

arquillian-create-test --deploymentTestable true/false

WDYT?

**Comment by gastaldi** [comment]
Or just --testable

**Comment by aslakknutsen** [comment]
Until some more 'know what your doing logic' is in place, --testable sounds good. :)

**Comment by danielsoro** [comment]
Nice!

I'll do later at home. :)

**Comment by lincolnthree** [comment]
Awesome! Make sure you use the @WithAttributes(description="") to
appropriately describe what the feature does!

On Wed, Dec 17, 2014 at 8:49 AM, Daniel Cunha (soro) <
notifications@github.com> wrote:

> Nice!
> 
> I'll do later at home. :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/forge/addon-arquillian/pull/1#issuecomment-67324040.

## 

Lincoln Baxter, III
http://ocpsoft.org
"Simpler is better."

**Comment by gastaldi** [comment]
Also, make sure that it is "true" by default

**Comment by danielsoro** [comment]
Fixed.
But I found 2 problems (I think): 
https://issues.jboss.org/browse/FORGE-2170
https://issues.jboss.org/browse/FORGE-2171

**Comment by gastaldi** [comment]
They are fixed now. Could you rebase?

**Comment by gastaldi** [comment]
It would be nice to add the testable attribute ONLY if testable == false

**Comment by danielsoro** [comment]
I need to change PR for #3

**Pull request closed without merging**
