### PR TITLE
adds container configuration test and increase timeouts

### PR DESCRIPTION
**Pull request by lordofthejars**

### CODE REVIEW

**Comment by gastaldi** [comment]
Add to whitelist

**Comment by bartoszmajsak** [comment]
We still have timeouts on jenkins @lordofthejars

**Review by bartoszmajsak — APPROVED** [review]
Fix the build. Other than that LGTM

**Comment by lordofthejars** [comment]
I have increased timeouts to 30 seconds but in Jenkins still fails.

**Comment by gastaldi** [comment]
Can you run the build locally without errors? Not sure if increasing the timeout is the solution. Maybe an uncaught error is being thrown

**Comment by lordofthejars** [comment]
Locally it works, and in travis works as well. @bartoszmajsak can you try this on your machine?

**Comment by bartoszmajsak** [comment]
```bash
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:35 min
[INFO] Finished at: 2017-01-04T14:48:15+01:00
[INFO] Final Memory: 43M/939M
[INFO] ------------------------------------------------------------------------
addon-arquillian [mvn clean install]
```

**Comment by lordofthejars** [comment]
@bartoszmajsak thanks. Great, let me increase to 1 minute this specific test and see

**Comment by gastaldi** [comment]
Interesting that Travis build passes. This is really weird

**Comment by lordofthejars** [comment]
@gastaldi travis and also our local computers, bow I have increased to 2 minutes if not work then we will need to explore what is happening in Jenkins.

**Comment by lordofthejars** [comment]
@bartoszmajsak how about ignoring the test it always fails in jenkins?

**Comment by bartoszmajsak** [comment]
Well to be honest if we ignore there is no point of keeping it at all... Either we fix it / rewrite it or we delete it.

**Comment by lordofthejars** [comment]
well I would not remove because it works on travis and local machines so during release we can uncomment it to be sure that testng still works. Rewriting I don't know how to do it.

**Comment by bartoszmajsak** [comment]
As you can see it failed on travis last time :)

**Pull request merged**
