### PR TITLE
Fixed: FORGEPLUGINS-174 Make the generated test testable in container

### PR DESCRIPTION
**Pull request by danielsoro**

### CODE REVIEW

**Comment by gastaldi** [comment]
How about adding the testable flag only if testable == false? I think another approach would be to call it --non-testable

**Comment by lordofthejars** [comment]
I think that since by default this flag is true, what @gastaldi suggests has sense of using a monotype flag called `--non-testable`

**Comment by lordofthejars** [comment]
Also I miss a test (see https://github.com/forge/addon-arquillian/pull/7)

**Comment by lordofthejars** [comment]
@danielsoro in wildfly swarm we called this flag `--asClient`. I am very interested in this feature you are providing, if you want I can fix the missing test.

**Comment by bartoszmajsak** [comment]
Revised version of this PR will come from [as-client](https://github.com/forge/addon-arquillian/tree/as_client) branch. Thanks @danielsoro for your contribution!

**Pull request closed without merging**
