### PR TITLE
Delete .travis.yml

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Do we have notifications from cloudbees integrated? Let's use this PR to see that in action.

**Comment by gastaldi** [comment]
That's what I am trying to set up. Not sure why it works on forge/core and
not in this repo. Will investigate further

Em 4 de jan de 2017 10:57, "Bartosz Majsak" <notifications@github.com>
escreveu:

**Comment by gastaldi** [comment]
Retest this please

**Comment by gastaldi** [comment]
Retest this please

**Comment by gastaldi** [comment]
Ok to test

**Comment by gastaldi** [comment]
Retest this please

**Comment by gastaldi** [comment]
Retest this please

**Comment by gastaldi** [comment]
Integration is working now

**Comment by bartoszmajsak** [comment]
Both travis and cloudbees works. What was the problem?

**Comment by gastaldi** [comment]
Authentication missing in Cbees and authorization in Travis

**Comment by lordofthejars** [comment]
If we remove travis, then we need to change CloudBees script to just run `mvn clean test -P ci` to excluding TestNG test

**Comment by gastaldi** [comment]
Closing as it has conflicts (!)

**Pull request closed without merging**
