### PR TITLE
Adds Configure Algeron Provider dependencies.

### PR DESCRIPTION
**Pull request by dipak-pawar**
This adds `Configure Algeron Provider dependencies` command to forge.

### CODE REVIEW

**Comment by lordofthejars** [comment]
Why there is no CI output?

One thing you are using the old format. It is not a problem we can fix it later.

**Comment by bartoszmajsak** [comment]
> Why there is no CI output?

If you mean build result - you have to trigger it manually.

**Comment by bartoszmajsak** [comment]
Retest this please

**Comment by dipak-pawar** [comment]
Retest this please

**Comment by bartoszmajsak** [comment]
Retest this please

**Comment by bartoszmajsak** [comment]
Retest this please

**Comment by bartoszmajsak** [comment]
Retest this please

**Pull request merged**
